### ISSUE TITLE
CQimage不能更换表情包

### ISSUE THREAD

**Issue by Zhouzerong233** [fz6m/nonebot-plugin#1]
在初次使用过程中发现不能更换表情包

![3hkWa8.png](https://s2.ax1x.com/2020/03/03/3hkWa8.png)

需要手动在`image_data/`下手动新建一个`qqdata`文件夹

**Comment by fz6m** [comment]
感谢反馈。
是空文件夹没有同步上，rar文件夹内的压缩包不存在这个问题，已修复。

**Comment by Zhouzerong233** [comment]
又发现个小问题😂

在`__init__.py`里
~~~py
 else:
        if msg.find("Img")!=-1 or msg.find("img")!=-1:        <-这里
            mark = await get.setQqName(qq,msg)
~~~
这里改关键词是不能正常使用的，还要在`get.py`的
~~~py
async def setQqName(qq,msg):
    item=0
    msg=str(msg)
    msg_list = msg.split(" ")
    if msg_list[0]=="img":                                   <-这里
        mark = str(await getQqName(qq))
        msg = msg_list[1]
        p="image_data/qqdata/"+str(qq)+".ini"
        name = "image_data/bieming/name.ini"
~~~
修改才行

也就是说，原来那里的关键词`Img`是无法使用的

**Comment by fz6m** [comment]
hhh不愧是你，感谢反馈。

**Comment by Zhouzerong233** [comment]
请问一下，没有设定之前的表情包是哪一张？怎么改？

**Comment by Zhouzerong233** [comment]
> 请问一下，没有设定之前的表情包是哪一张？怎么改？

我找到了，initial

**Comment by Zhouzerong233** [comment]
不好意思，我又来了，还是改图里的问题，某一张特定的图片不能改回来，如果手动改qqdata里的文件是能正常制作图片的

![3553E6.png](https://s2.ax1x.com/2020/03/04/3553E6.png)

**Comment by fz6m** [comment]
要通过 bieming 文件内配置的别名才可以改，你可以看下插件[使用说明](https://fz6m.github.io/plugin-press/cqp/image.html#%E7%94%A8%E6%88%B7%E6%9B%B4%E6%8D%A2%E8%A1%A8%E6%83%85%E5%8C%85)。

**Comment by Zhouzerong233** [comment]
别名已经改了

**Comment by fz6m** [comment]
新设表情包要保持 文件夹名 config配置文件内name 别名配置文件内第二个字段 三个一样

**Comment by Zhouzerong233** [comment]
![35opmn.png](https://s2.ax1x.com/2020/03/04/35opmn.png)

![35IzOs.png](https://s2.ax1x.com/2020/03/04/35IzOs.png)

**Comment by fz6m** [comment]
你如果改动过代码，自己查下代码逻辑吧，这个很简单。我没遇到过你这个情况，用的好好的emmm

**Comment by Zhouzerong233** [comment]
好吧，查出来了跟你反馈一下，另外有没有可能是中文关键词的问题？我也有别的报错
~~~
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
~~~
看起来像是编码问题，然而我没学过python，不知道这种情况应该怎么处理

**Comment by fz6m** [comment]
读写文件的时候加上参数 encoding = 'utf-8'，每台机器环境不一样会有这样的问题，可以参考[这里](https://blog.csdn.net/qq_16761099/article/details/80559302)

**Comment by Zhouzerong233** [comment]
查到了！！！

![3579iV.png](https://s2.ax1x.com/2020/03/04/3579iV.png)

这里读取用的gbk，写入又用的utf-8，中文关键词解决了

然而上述ars1的表情包改不了的问题还是存在
